---
- name: config elk server
  hosts: elk
  remote_user: azureuser
  become: true
  tasks:
  
    - name: set vm max map count
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes

    - name: docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: install python docker module
      pip:
        name: docker
        state: present

    - name: download and launch a docker web container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - '5601:5601'
          - '9200:9200'
          - '5044:5044'

    - name: enable docker service
      systemd:
        name: docker
        enabled: yes
    
