---
- name: installing metric beat
  hosts: webservers
  become: true
  tasks:

  - name: donwload metric beat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: install metric beat
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: dropin metricbeat config
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module
    command: sudo metricbeat modules enable docker

  - name: setup metricbeat
    command: sudo metricbeat setup

  - name: start metricbeat
    command: sudo service metricbeat start

  - name: enable service filebeat on boot
    systemd:
      name: metricbeat
      enabled: yes
